# LOADING THE INPUT IMAGE FOR DECIDING THE THRESHOLD
# RESIZING IT AND THEN CONVERTING TO GREYSCALE
img <- load.image("C:\\Users\\sbtrader\\Downloads\\milind.jpg") %>%
  resize(700, 500) %>%
  grayscale()

# PLOTTING THE IMAGE FOR CONFIRMATION
plot(img)

# CONVERTING THE IMAGE INTO A MATRIX FORMAT
imgGSMat <- img %>% as.matrix() %>% t()

# PLOTTING THE SUMMARY OF THE INPUT ARRAY
# TO GET THE SENSE OF DISTRIBUTION
summary(c(imgGSMat))

# PLOTTING THE IMAGE FILE WITH THRESHOLD
# THIS CAN BE A TRIAL AND ERROR METHOD
plot(as.cimg(imgGSMat > 0.0015))
